name: pos_project
description: "A new Flutter project."


publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.7.0


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.7.2
  http:
  shared_preferences: ^2.5.2
  responsive_builder: ^0.7.1
  device_preview: ^1.2.0
  cached_network_image: ^3.2.3
  decimal: ^2.3.3
  timeline_tile: ^2.0.0
  dotted_border: ^2.1.0
  dio: ^5.8.0+1
  intl:
  printing: ^5.14.2
  pdf: ^3.11.3
  country_currency_pickers: ^3.0.0
  flutter_barcode_sdk: ^2.2.6
  mobile_scanner: ^6.0.7
  permission_handler: ^11.3.1
  screenshot: ^3.0.0
  rotated_corner_decoration: ^2.1.0+1
  connectivity_plus: ^6.1.3
  internet_connection_checker_plus: ^2.7.1
  audioplayers: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/
    - assets/sounds/
