import 'package:http/http.dart' as http;
import 'dart:convert';

import '../../Locale_Memory/save_user_info_locally.dart';
import '../../const/urls.dart';

Future getAllProducts(
  String searchByName,
  String searchByCat,
  String posProducts,
  String warehouseId,
  String barcode,
  int currentPage,
) async {
  // print('searchByName $searchByName');
  // print('posProducts $posProducts');
  // print('warehouseId $warehouseId');
  // print('barcode $barcode');
  Map<String, dynamic> params =
      currentPage == -1
          ? {
            'search': searchByName,
            'searchByCat': searchByCat,
            'isPaginated': '0',
            'posProducts': posProducts,
            'onlyActive': '1',
            'warehouseId': warehouseId,
            'barcode': barcode,
          }
          : {
            'search': searchByName,
            'searchByCat': searchByCat,
            'isPaginated': '1',
            'perPage': '20',
            'page': '$currentPage',
            'posProducts': posProducts,
            'onlyActive': '1',
            'warehouseId': warehouseId,
            'barcode': barcode,
          };
  final uri = Uri.parse(kGetAllProductsUrl).replace(queryParameters: params);
  String token = await getAccessTokenFromPref();
  var response = await http.get(
    uri,
    headers: {"Accept": "application/json", "Authorization": "Bearer $token"},
  );

  var p = json.decode(response.body);
  // print('object $p');
  if (response.statusCode == 200) {
    return p['data'];
  } else {
    return [];
  }
}

//
//
// var products= [
//   {
//     "id": 1,
//     "company": {
//       "id": 1,
//       "name": "Code Caesar",
//       "active": 1,
//       "deleted_at": null,
//       "created_at": "2023-07-19T16:18:12.000000Z",
//       "updated_at": "2023-07-19T16:18:12.000000Z"
//     },
//     "warehouse": {
//       "id": 1,
//       "company_id": 1,
//       "name": "CENTRAL",
//       "active": 1,
//       "created_at": "2023-08-02T03:08:23.000000Z",
//       "updated_at": "2023-08-02T03:08:23.000000Z",
//       "deleted_at": null
//     },
//     "itemType": {
//       "id": 3,
//       "name": "With SubRef",
//       "created_at": "2023-07-19T16:06:10.000000Z",
//       "updated_at": "2023-07-19T16:06:10.000000Z"
//     },
//     "mainCode": "123",
//     "printMainCode": 0,
//     "taxation": null,
//     "subref_id": {
//       "id": 1,
//       "name": "Serial Number",
//       "created_at": "2023-07-19T16:06:10.000000Z",
//       "updated_at": "2023-07-19T16:06:10.000000Z"
//     },
//     "canBeSold": 1,
//     "canBePurchased": 1,
//     "warranty": 0,
//     "lastAllowedPurchaseDate": null,
//     "shortDescription": "456789",
//     "mainDescription": "456789789789789",
//     "secondLanguageDescription": null,
//     "supplierCodes": [
//       {
//         "id": 1,
//         "code": "456789888888",
//         "print_code": null,
//         "company_id": 1,
//         "item_id": 1,
//         "created_at": "2023-08-02T03:10:59.000000Z",
//         "updated_at": "2023-08-02T03:10:59.000000Z",
//         "deleted_at": null
//       }
//     ],
//     "alternativeCodes": [],
//     "barcode": [],
//     "unitCost": null,
//     "decimalCost": null,
//     "currency": {
//       "id": 1,
//       "company_id": null,
//       "name": "USD",
//       "symbol": "\$",
//       "active": 1,
//       "created_at": "2023-07-19T16:19:56.000000Z",
//       "updated_at": "2023-07-19T16:19:56.000000Z",
//       "deleted_at": null
//     },
//     "quantity": null,
//     "unitPrice": 15,
//     "decimalPrice": null,
//     "lineDiscountLimit": 10,
//     "packageType": 2,
//     "packageUnitName": "PCS",
//     "packageUnitQuantity": "24",
//     "packageSetName": "BOX",
//     "packageSetQuantity": "1",
//     "packageSupersetName": null,
//     "packageSupersetQuantity": null,
//     "packagePaletteName": null,
//     "packagePaletteQuantity": null,
//     "packageContainerName": null,
//     "packageContainerQuantity": null,
//     "decimalQuantity": null,
//     "active": 1
//   },
//   {
//     "id": 12,
//     "company": {
//       "id": 1,
//       "name": "Code Caesar",
//       "active": 1,
//       "deleted_at": null,
//       "created_at": "2023-07-19T16:18:12.000000Z",
//       "updated_at": "2023-07-19T16:18:12.000000Z"
//     },
//     "warehouse": null,
//     "itemType": {
//       "id": 1,
//       "name": "Regular",
//       "created_at": "2023-07-19T16:06:10.000000Z",
//       "updated_at": "2023-07-19T16:06:10.000000Z"
//     },
//     "mainCode": "ssws",
//     "printMainCode": null,
//     "taxation": null,
//     "subref_id": null,
//     "canBeSold": 1,
//     "canBePurchased": 1,
//     "warranty": 1,
//     "lastAllowedPurchaseDate": null,
//     "shortDescription": null,
//     "mainDescription": null,
//     "secondLanguageDescription": null,
//     "supplierCodes": [],
//     "alternativeCodes": [],
//     "barcode": [],
//     "unitCost": 1,
//     "decimalCost": null,
//     "currency": null,
//     "quantity": null,
//     "unitPrice": null,
//     "decimalPrice": null,
//     "lineDiscountLimit": null,
//     "packageType": null,
//     "packageUnitName": null,
//     "packageUnitQuantity": null,
//     "packageSetName": null,
//     "packageSetQuantity": null,
//     "packageSupersetName": null,
//     "packageSupersetQuantity": null,
//     "packagePaletteName": null,
//     "packagePaletteQuantity": null,
//     "packageContainerName": null,
//     "packageContainerQuantity": null,
//     "decimalQuantity": null,
//     "active": 1
//   },
//   {
//     "id": 13,
//     "company": {
//       "id": 1,
//       "name": "Code Caesar",
//       "active": 1,
//       "deleted_at": null,
//       "created_at": "2023-07-19T16:18:12.000000Z",
//       "updated_at": "2023-07-19T16:18:12.000000Z"
//     },
//     "warehouse": null,
//     "itemType": {
//       "id": 1,
//       "name": "Regular",
//       "created_at": "2023-07-19T16:06:10.000000Z",
//       "updated_at": "2023-07-19T16:06:10.000000Z"
//     },
//     "mainCode": "swsw",
//     "printMainCode": null,
//     "taxation": null,
//     "subref_id": null,
//     "canBeSold": 1,
//     "canBePurchased": 1,
//     "warranty": 1,
//     "lastAllowedPurchaseDate": null,
//     "shortDescription": null,
//     "mainDescription": null,
//     "secondLanguageDescription": null,
//     "supplierCodes": [],
//     "alternativeCodes": [],
//     "barcode": [],
//     "unitCost": null,
//     "decimalCost": null,
//     "currency": {
//       "id": 3,
//       "company_id": 1,
//       "name": "USD",
//       "symbol": "\$",
//       "active": 1,
//       "created_at": "2023-09-26T19:08:01.000000Z",
//       "updated_at": "2023-09-26T19:08:01.000000Z",
//       "deleted_at": null
//     },
//     "quantity": null,
//     "unitPrice": null,
//     "decimalPrice": null,
//     "lineDiscountLimit": null,
//     "packageType": null,
//     "packageUnitName": null,
//     "packageUnitQuantity": null,
//     "packageSetName": null,
//     "packageSetQuantity": null,
//     "packageSupersetName": null,
//     "packageSupersetQuantity": null,
//     "packagePaletteName": null,
//     "packagePaletteQuantity": null,
//     "packageContainerName": null,
//     "packageContainerQuantity": null,
//     "decimalQuantity": null,
//     "active": 1
//   },
//   {
//     "id": 14,
//     "company": {
//       "id": 1,
//       "name": "Code Caesar",
//       "active": 1,
//       "deleted_at": null,
//       "created_at": "2023-07-19T16:18:12.000000Z",
//       "updated_at": "2023-07-19T16:18:12.000000Z"
//     },
//     "warehouse": null,
//     "itemType": {
//       "id": 1,
//       "name": "Regular",
//       "created_at": "2023-07-19T16:06:10.000000Z",
//       "updated_at": "2023-07-19T16:06:10.000000Z"
//     },
//     "mainCode": "swqwq",
//     "printMainCode": null,
//     "taxation": null,
//     "subref_id": null,
//     "canBeSold": 0,
//     "canBePurchased": 0,
//     "warranty": 0,
//     "lastAllowedPurchaseDate": null,
//     "shortDescription": null,
//     "mainDescription": null,
//     "secondLanguageDescription": null,
//     "supplierCodes": [],
//     "alternativeCodes": [],
//     "barcode": [],
//     "unitCost": null,
//     "decimalCost": null,
//     "currency": {
//       "id": 3,
//       "company_id": 1,
//       "name": "USD",
//       "symbol": "\$",
//       "active": 1,
//       "created_at": "2023-09-26T19:08:01.000000Z",
//       "updated_at": "2023-09-26T19:08:01.000000Z",
//       "deleted_at": null
//     },
//     "quantity": null,
//     "unitPrice": null,
//     "decimalPrice": null,
//     "lineDiscountLimit": null,
//     "packageType": null,
//     "packageUnitName": null,
//     "packageUnitQuantity": null,
//     "packageSetName": null,
//     "packageSetQuantity": null,
//     "packageSupersetName": null,
//     "packageSupersetQuantity": null,
//     "packagePaletteName": null,
//     "packagePaletteQuantity": null,
//     "packageContainerName": null,
//     "packageContainerQuantity": null,
//     "decimalQuantity": null,
//     "active": 1
//   },
//   {
//     "id": 15,
//     "company": {
//       "id": 1,
//       "name": "Code Caesar",
//       "active": 1,
//       "deleted_at": null,
//       "created_at": "2023-07-19T16:18:12.000000Z",
//       "updated_at": "2023-07-19T16:18:12.000000Z"
//     },
//     "warehouse": null,
//     "itemType": {
//       "id": 1,
//       "name": "Regular",
//       "created_at": "2023-07-19T16:06:10.000000Z",
//       "updated_at": "2023-07-19T16:06:10.000000Z"
//     },
//     "mainCode": "www",
//     "printMainCode": null,
//     "taxation": null,
//     "subref_id": null,
//     "canBeSold": 0,
//     "canBePurchased": 0,
//     "warranty": 0,
//     "lastAllowedPurchaseDate": null,
//     "shortDescription": null,
//     "mainDescription": null,
//     "secondLanguageDescription": null,
//     "supplierCodes": [],
//     "alternativeCodes": [],
//     "barcode": [],
//     "unitCost": null,
//     "decimalCost": null,
//     "currency": {
//       "id": 3,
//       "company_id": 1,
//       "name": "USD",
//       "symbol": "\$",
//       "active": 1,
//       "created_at": "2023-09-26T19:08:01.000000Z",
//       "updated_at": "2023-09-26T19:08:01.000000Z",
//       "deleted_at": null
//     },
//     "quantity": null,
//     "unitPrice": null,
//     "decimalPrice": null,
//     "lineDiscountLimit": null,
//     "packageType": null,
//     "packageUnitName": null,
//     "packageUnitQuantity": null,
//     "packageSetName": null,
//     "packageSetQuantity": null,
//     "packageSupersetName": null,
//     "packageSupersetQuantity": null,
//     "packagePaletteName": null,
//     "packagePaletteQuantity": null,
//     "packageContainerName": null,
//     "packageContainerQuantity": null,
//     "decimalQuantity": null,
//     "active": 1
//   },
//   {
//     "id": 16,
//     "company": {
//       "id": 1,
//       "name": "Code Caesar",
//       "active": 1,
//       "deleted_at": null,
//       "created_at": "2023-07-19T16:18:12.000000Z",
//       "updated_at": "2023-07-19T16:18:12.000000Z"
//     },
//     "warehouse": null,
//     "itemType": {
//       "id": 1,
//       "name": "Regular",
//       "created_at": "2023-07-19T16:06:10.000000Z",
//       "updated_at": "2023-07-19T16:06:10.000000Z"
//     },
//     "mainCode": "swwww",
//     "printMainCode": null,
//     "taxation": null,
//     "subref_id": null,
//     "canBeSold": 0,
//     "canBePurchased": 0,
//     "warranty": 0,
//     "lastAllowedPurchaseDate": null,
//     "shortDescription": null,
//     "mainDescription": null,
//     "secondLanguageDescription": null,
//     "supplierCodes": [],
//     "alternativeCodes": [],
//     "barcode": [],
//     "unitCost": null,
//     "decimalCost": null,
//     "currency": {
//       "id": 3,
//       "company_id": 1,
//       "name": "USD",
//       "symbol": "\$",
//       "active": 1,
//       "created_at": "2023-09-26T19:08:01.000000Z",
//       "updated_at": "2023-09-26T19:08:01.000000Z",
//       "deleted_at": null
//     },
//     "quantity": null,
//     "unitPrice": null,
//     "decimalPrice": null,
//     "lineDiscountLimit": null,
//     "packageType": null,
//     "packageUnitName": null,
//     "packageUnitQuantity": null,
//     "packageSetName": null,
//     "packageSetQuantity": null,
//     "packageSupersetName": null,
//     "packageSupersetQuantity": null,
//     "packagePaletteName": null,
//     "packagePaletteQuantity": null,
//     "packageContainerName": null,
//     "packageContainerQuantity": null,
//     "decimalQuantity": null,
//     "active": 1
//   },
//   {
//     "id": 17,
//     "company": {
//       "id": 1,
//       "name": "Code Caesar",
//       "active": 1,
//       "deleted_at": null,
//       "created_at": "2023-07-19T16:18:12.000000Z",
//       "updated_at": "2023-07-19T16:18:12.000000Z"
//     },
//     "warehouse": null,
//     "itemType": {
//       "id": 1,
//       "name": "Regular",
//       "created_at": "2023-07-19T16:06:10.000000Z",
//       "updated_at": "2023-07-19T16:06:10.000000Z"
//     },
//     "mainCode": "dedede",
//     "printMainCode": 1,
//     "taxation": null,
//     "subref_id": null,
//     "canBeSold": 0,
//     "canBePurchased": 0,
//     "warranty": 0,
//     "lastAllowedPurchaseDate": null,
//     "shortDescription": null,
//     "mainDescription": null,
//     "secondLanguageDescription": null,
//     "supplierCodes": [],
//     "alternativeCodes": [],
//     "barcode": [],
//     "unitCost": null,
//     "decimalCost": null,
//     "currency": {
//       "id": 3,
//       "company_id": 1,
//       "name": "USD",
//       "symbol": "\$",
//       "active": 1,
//       "created_at": "2023-09-26T19:08:01.000000Z",
//       "updated_at": "2023-09-26T19:08:01.000000Z",
//       "deleted_at": null
//     },
//     "quantity": null,
//     "unitPrice": null,
//     "decimalPrice": null,
//     "lineDiscountLimit": null,
//     "packageType": null,
//     "packageUnitName": null,
//     "packageUnitQuantity": null,
//     "packageSetName": null,
//     "packageSetQuantity": null,
//     "packageSupersetName": null,
//     "packageSupersetQuantity": null,
//     "packagePaletteName": null,
//     "packagePaletteQuantity": null,
//     "packageContainerName": null,
//     "packageContainerQuantity": null,
//     "decimalQuantity": null,
//     "active": 1
//   },
//   {
//     "id": 18,
//     "company": {
//       "id": 1,
//       "name": "Code Caesar",
//       "active": 1,
//       "deleted_at": null,
//       "created_at": "2023-07-19T16:18:12.000000Z",
//       "updated_at": "2023-07-19T16:18:12.000000Z"
//     },
//     "warehouse": null,
//     "itemType": {
//       "id": 1,
//       "name": "Regular",
//       "created_at": "2023-07-19T16:06:10.000000Z",
//       "updated_at": "2023-07-19T16:06:10.000000Z"
//     },
//     "mainCode": "swqqqqqqq",
//     "printMainCode": 1,
//     "taxation": null,
//     "subref_id": null,
//     "canBeSold": 0,
//     "canBePurchased": 0,
//     "warranty": 0,
//     "lastAllowedPurchaseDate": null,
//     "shortDescription": null,
//     "mainDescription": null,
//     "secondLanguageDescription": null,
//     "supplierCodes": [],
//     "alternativeCodes": [],
//     "barcode": [],
//     "unitCost": null,
//     "decimalCost": null,
//     "currency": {
//       "id": 3,
//       "company_id": 1,
//       "name": "USD",
//       "symbol": "\$",
//       "active": 1,
//       "created_at": "2023-09-26T19:08:01.000000Z",
//       "updated_at": "2023-09-26T19:08:01.000000Z",
//       "deleted_at": null
//     },
//     "quantity": null,
//     "unitPrice": null,
//     "decimalPrice": null,
//     "lineDiscountLimit": null,
//     "packageType": null,
//     "packageUnitName": null,
//     "packageUnitQuantity": null,
//     "packageSetName": null,
//     "packageSetQuantity": null,
//     "packageSupersetName": null,
//     "packageSupersetQuantity": null,
//     "packagePaletteName": null,
//     "packagePaletteQuantity": null,
//     "packageContainerName": null,
//     "packageContainerQuantity": null,
//     "decimalQuantity": null,
//     "active": 1
//   },
//   {
//     "id": 19,
//     "company": {
//       "id": 1,
//       "name": "Code Caesar",
//       "active": 1,
//       "deleted_at": null,
//       "created_at": "2023-07-19T16:18:12.000000Z",
//       "updated_at": "2023-07-19T16:18:12.000000Z"
//     },
//     "warehouse": null,
//     "itemType": {
//       "id": 1,
//       "name": "Regular",
//       "created_at": "2023-07-19T16:06:10.000000Z",
//       "updated_at": "2023-07-19T16:06:10.000000Z"
//     },
//     "mainCode": "aaaaaaa",
//     "printMainCode": 1,
//     "taxation": null,
//     "subref_id": null,
//     "canBeSold": 0,
//     "canBePurchased": 0,
//     "warranty": 0,
//     "lastAllowedPurchaseDate": null,
//     "shortDescription": null,
//     "mainDescription": null,
//     "secondLanguageDescription": null,
//     "supplierCodes": [],
//     "alternativeCodes": [],
//     "barcode": [],
//     "unitCost": null,
//     "decimalCost": null,
//     "currency": {
//       "id": 3,
//       "company_id": 1,
//       "name": "USD",
//       "symbol": "\$",
//       "active": 1,
//       "created_at": "2023-09-26T19:08:01.000000Z",
//       "updated_at": "2023-09-26T19:08:01.000000Z",
//       "deleted_at": null
//     },
//     "quantity": null,
//     "unitPrice": null,
//     "decimalPrice": null,
//     "lineDiscountLimit": null,
//     "packageType": null,
//     "packageUnitName": null,
//     "packageUnitQuantity": null,
//     "packageSetName": null,
//     "packageSetQuantity": null,
//     "packageSupersetName": null,
//     "packageSupersetQuantity": null,
//     "packagePaletteName": null,
//     "packagePaletteQuantity": null,
//     "packageContainerName": null,
//     "packageContainerQuantity": null,
//     "decimalQuantity": null,
//     "active": 1
//   },
//   {
//     "id": 20,
//     "company": {
//       "id": 1,
//       "name": "Code Caesar",
//       "active": 1,
//       "deleted_at": null,
//       "created_at": "2023-07-19T16:18:12.000000Z",
//       "updated_at": "2023-07-19T16:18:12.000000Z"
//     },
//     "warehouse": null,
//     "itemType": {
//       "id": 1,
//       "name": "Regular",
//       "created_at": "2023-07-19T16:06:10.000000Z",
//       "updated_at": "2023-07-19T16:06:10.000000Z"
//     },
//     "mainCode": "llllll",
//     "printMainCode": 1,
//     "taxation": null,
//     "subref_id": null,
//     "canBeSold": 0,
//     "canBePurchased": 0,
//     "warranty": 0,
//     "lastAllowedPurchaseDate": null,
//     "shortDescription": null,
//     "mainDescription": null,
//     "secondLanguageDescription": null,
//     "supplierCodes": [],
//     "alternativeCodes": [],
//     "barcode": [],
//     "unitCost": null,
//     "decimalCost": null,
//     "currency": {
//       "id": 3,
//       "company_id": 1,
//       "name": "USD",
//       "symbol": "\$",
//       "active": 1,
//       "created_at": "2023-09-26T19:08:01.000000Z",
//       "updated_at": "2023-09-26T19:08:01.000000Z",
//       "deleted_at": null
//     },
//     "quantity": null,
//     "unitPrice": null,
//     "decimalPrice": null,
//     "lineDiscountLimit": null,
//     "packageType": null,
//     "packageUnitName": null,
//     "packageUnitQuantity": null,
//     "packageSetName": null,
//     "packageSetQuantity": null,
//     "packageSupersetName": null,
//     "packageSupersetQuantity": null,
//     "packagePaletteName": null,
//     "packagePaletteQuantity": null,
//     "packageContainerName": null,
//     "packageContainerQuantity": null,
//     "decimalQuantity": null,
//     "active": 1
//   }
// ];
// // {
// //   "data": [
// //     {
// //       "id": 1,
// //       "company": {
// //         "id": 1,
// //         "name": "Code Caesar",
// //         "active": 1,
// //         "deleted_at": null,
// //         "created_at": "2023-07-19T16:18:12.000000Z",
// //         "updated_at": "2023-07-19T16:18:12.000000Z"
// //       },
// //       "warehouse": {
// //         "id": 1,
// //         "company_id": 1,
// //         "name": "CENTRAL",
// //         "active": 1,
// //         "created_at": "2023-08-02T03:08:23.000000Z",
// //         "updated_at": "2023-08-02T03:08:23.000000Z",
// //         "deleted_at": null
// //       },
// //       "itemType": {
// //         "id": 3,
// //         "name": "With SubRef",
// //         "created_at": "2023-07-19T16:06:10.000000Z",
// //         "updated_at": "2023-07-19T16:06:10.000000Z"
// //       },
// //       "mainCode": "123",
// //       "printMainCode": 0,
// //       "taxation": null,
// //       "subref_id": {
// //         "id": 1,
// //         "name": "Serial Number",
// //         "created_at": "2023-07-19T16:06:10.000000Z",
// //         "updated_at": "2023-07-19T16:06:10.000000Z"
// //       },
// //       "canBeSold": 1,
// //       "canBePurchased": 1,
// //       "warranty": 0,
// //       "lastAllowedPurchaseDate": null,
// //       "shortDescription": "456789",
// //       "mainDescription": "456789789789789",
// //       "secondLanguageDescription": null,
// //       "supplierCodes": [
// //         {
// //           "id": 1,
// //           "code": "456789888888",
// //           "print_code": null,
// //           "company_id": 1,
// //           "item_id": 1,
// //           "created_at": "2023-08-02T03:10:59.000000Z",
// //           "updated_at": "2023-08-02T03:10:59.000000Z",
// //           "deleted_at": null
// //         }
// //       ],
// //       "alternativeCodes": [],
// //       "barcode": [],
// //       "unitCost": null,
// //       "decimalCost": null,
// //       "currency": {
// //         "id": 1,
// //         "company_id": null,
// //         "name": "USD",
// //         "symbol": "\$",
// //         "active": 1,
// //         "created_at": "2023-07-19T16:19:56.000000Z",
// //         "updated_at": "2023-07-19T16:19:56.000000Z",
// //         "deleted_at": null
// //       },
// //       "quantity": null,
// //       "unitPrice": 15,
// //       "decimalPrice": null,
// //       "lineDiscountLimit": 10,
// //       "packageType": 2,
// //       "packageUnitName": "PCS",
// //       "packageUnitQuantity": "24",
// //       "packageSetName": "BOX",
// //       "packageSetQuantity": "1",
// //       "packageSupersetName": null,
// //       "packageSupersetQuantity": null,
// //       "packagePaletteName": null,
// //       "packagePaletteQuantity": null,
// //       "packageContainerName": null,
// //       "packageContainerQuantity": null,
// //       "decimalQuantity": null,
// //       "active": 1
// //     },
// //     {
// //       "id": 12,
// //       "company": {
// //         "id": 1,
// //         "name": "Code Caesar",
// //         "active": 1,
// //         "deleted_at": null,
// //         "created_at": "2023-07-19T16:18:12.000000Z",
// //         "updated_at": "2023-07-19T16:18:12.000000Z"
// //       },
// //       "warehouse": null,
// //       "itemType": {
// //         "id": 1,
// //         "name": "Regular",
// //         "created_at": "2023-07-19T16:06:10.000000Z",
// //         "updated_at": "2023-07-19T16:06:10.000000Z"
// //       },
// //       "mainCode": "ssws",
// //       "printMainCode": null,
// //       "taxation": null,
// //       "subref_id": null,
// //       "canBeSold": 1,
// //       "canBePurchased": 1,
// //       "warranty": 1,
// //       "lastAllowedPurchaseDate": null,
// //       "shortDescription": null,
// //       "mainDescription": null,
// //       "secondLanguageDescription": null,
// //       "supplierCodes": [],
// //       "alternativeCodes": [],
// //       "barcode": [],
// //       "unitCost": 1,
// //       "decimalCost": null,
// //       "currency": null,
// //       "quantity": null,
// //       "unitPrice": null,
// //       "decimalPrice": null,
// //       "lineDiscountLimit": null,
// //       "packageType": null,
// //       "packageUnitName": null,
// //       "packageUnitQuantity": null,
// //       "packageSetName": null,
// //       "packageSetQuantity": null,
// //       "packageSupersetName": null,
// //       "packageSupersetQuantity": null,
// //       "packagePaletteName": null,
// //       "packagePaletteQuantity": null,
// //       "packageContainerName": null,
// //       "packageContainerQuantity": null,
// //       "decimalQuantity": null,
// //       "active": 1
// //     },
// //     {
// //       "id": 13,
// //       "company": {
// //         "id": 1,
// //         "name": "Code Caesar",
// //         "active": 1,
// //         "deleted_at": null,
// //         "created_at": "2023-07-19T16:18:12.000000Z",
// //         "updated_at": "2023-07-19T16:18:12.000000Z"
// //       },
// //       "warehouse": null,
// //       "itemType": {
// //         "id": 1,
// //         "name": "Regular",
// //         "created_at": "2023-07-19T16:06:10.000000Z",
// //         "updated_at": "2023-07-19T16:06:10.000000Z"
// //       },
// //       "mainCode": "swsw",
// //       "printMainCode": null,
// //       "taxation": null,
// //       "subref_id": null,
// //       "canBeSold": 1,
// //       "canBePurchased": 1,
// //       "warranty": 1,
// //       "lastAllowedPurchaseDate": null,
// //       "shortDescription": null,
// //       "mainDescription": null,
// //       "secondLanguageDescription": null,
// //       "supplierCodes": [],
// //       "alternativeCodes": [],
// //       "barcode": [],
// //       "unitCost": null,
// //       "decimalCost": null,
// //       "currency": {
// //         "id": 3,
// //         "company_id": 1,
// //         "name": "USD",
// //         "symbol": "\$",
// //         "active": 1,
// //         "created_at": "2023-09-26T19:08:01.000000Z",
// //         "updated_at": "2023-09-26T19:08:01.000000Z",
// //         "deleted_at": null
// //       },
// //       "quantity": null,
// //       "unitPrice": null,
// //       "decimalPrice": null,
// //       "lineDiscountLimit": null,
// //       "packageType": null,
// //       "packageUnitName": null,
// //       "packageUnitQuantity": null,
// //       "packageSetName": null,
// //       "packageSetQuantity": null,
// //       "packageSupersetName": null,
// //       "packageSupersetQuantity": null,
// //       "packagePaletteName": null,
// //       "packagePaletteQuantity": null,
// //       "packageContainerName": null,
// //       "packageContainerQuantity": null,
// //       "decimalQuantity": null,
// //       "active": 1
// //     },
// //     {
// //       "id": 14,
// //       "company": {
// //         "id": 1,
// //         "name": "Code Caesar",
// //         "active": 1,
// //         "deleted_at": null,
// //         "created_at": "2023-07-19T16:18:12.000000Z",
// //         "updated_at": "2023-07-19T16:18:12.000000Z"
// //       },
// //       "warehouse": null,
// //       "itemType": {
// //         "id": 1,
// //         "name": "Regular",
// //         "created_at": "2023-07-19T16:06:10.000000Z",
// //         "updated_at": "2023-07-19T16:06:10.000000Z"
// //       },
// //       "mainCode": "swqwq",
// //       "printMainCode": null,
// //       "taxation": null,
// //       "subref_id": null,
// //       "canBeSold": 0,
// //       "canBePurchased": 0,
// //       "warranty": 0,
// //       "lastAllowedPurchaseDate": null,
// //       "shortDescription": null,
// //       "mainDescription": null,
// //       "secondLanguageDescription": null,
// //       "supplierCodes": [],
// //       "alternativeCodes": [],
// //       "barcode": [],
// //       "unitCost": null,
// //       "decimalCost": null,
// //       "currency": {
// //         "id": 3,
// //         "company_id": 1,
// //         "name": "USD",
// //         "symbol": "\$",
// //         "active": 1,
// //         "created_at": "2023-09-26T19:08:01.000000Z",
// //         "updated_at": "2023-09-26T19:08:01.000000Z",
// //         "deleted_at": null
// //       },
// //       "quantity": null,
// //       "unitPrice": null,
// //       "decimalPrice": null,
// //       "lineDiscountLimit": null,
// //       "packageType": null,
// //       "packageUnitName": null,
// //       "packageUnitQuantity": null,
// //       "packageSetName": null,
// //       "packageSetQuantity": null,
// //       "packageSupersetName": null,
// //       "packageSupersetQuantity": null,
// //       "packagePaletteName": null,
// //       "packagePaletteQuantity": null,
// //       "packageContainerName": null,
// //       "packageContainerQuantity": null,
// //       "decimalQuantity": null,
// //       "active": 1
// //     },
// //     {
// //       "id": 15,
// //       "company": {
// //         "id": 1,
// //         "name": "Code Caesar",
// //         "active": 1,
// //         "deleted_at": null,
// //         "created_at": "2023-07-19T16:18:12.000000Z",
// //         "updated_at": "2023-07-19T16:18:12.000000Z"
// //       },
// //       "warehouse": null,
// //       "itemType": {
// //         "id": 1,
// //         "name": "Regular",
// //         "created_at": "2023-07-19T16:06:10.000000Z",
// //         "updated_at": "2023-07-19T16:06:10.000000Z"
// //       },
// //       "mainCode": "www",
// //       "printMainCode": null,
// //       "taxation": null,
// //       "subref_id": null,
// //       "canBeSold": 0,
// //       "canBePurchased": 0,
// //       "warranty": 0,
// //       "lastAllowedPurchaseDate": null,
// //       "shortDescription": null,
// //       "mainDescription": null,
// //       "secondLanguageDescription": null,
// //       "supplierCodes": [],
// //       "alternativeCodes": [],
// //       "barcode": [],
// //       "unitCost": null,
// //       "decimalCost": null,
// //       "currency": {
// //         "id": 3,
// //         "company_id": 1,
// //         "name": "USD",
// //         "symbol": "\$",
// //         "active": 1,
// //         "created_at": "2023-09-26T19:08:01.000000Z",
// //         "updated_at": "2023-09-26T19:08:01.000000Z",
// //         "deleted_at": null
// //       },
// //       "quantity": null,
// //       "unitPrice": null,
// //       "decimalPrice": null,
// //       "lineDiscountLimit": null,
// //       "packageType": null,
// //       "packageUnitName": null,
// //       "packageUnitQuantity": null,
// //       "packageSetName": null,
// //       "packageSetQuantity": null,
// //       "packageSupersetName": null,
// //       "packageSupersetQuantity": null,
// //       "packagePaletteName": null,
// //       "packagePaletteQuantity": null,
// //       "packageContainerName": null,
// //       "packageContainerQuantity": null,
// //       "decimalQuantity": null,
// //       "active": 1
// //     },
// //     {
// //       "id": 16,
// //       "company": {
// //         "id": 1,
// //         "name": "Code Caesar",
// //         "active": 1,
// //         "deleted_at": null,
// //         "created_at": "2023-07-19T16:18:12.000000Z",
// //         "updated_at": "2023-07-19T16:18:12.000000Z"
// //       },
// //       "warehouse": null,
// //       "itemType": {
// //         "id": 1,
// //         "name": "Regular",
// //         "created_at": "2023-07-19T16:06:10.000000Z",
// //         "updated_at": "2023-07-19T16:06:10.000000Z"
// //       },
// //       "mainCode": "swwww",
// //       "printMainCode": null,
// //       "taxation": null,
// //       "subref_id": null,
// //       "canBeSold": 0,
// //       "canBePurchased": 0,
// //       "warranty": 0,
// //       "lastAllowedPurchaseDate": null,
// //       "shortDescription": null,
// //       "mainDescription": null,
// //       "secondLanguageDescription": null,
// //       "supplierCodes": [],
// //       "alternativeCodes": [],
// //       "barcode": [],
// //       "unitCost": null,
// //       "decimalCost": null,
// //       "currency": {
// //         "id": 3,
// //         "company_id": 1,
// //         "name": "USD",
// //         "symbol": "\$",
// //         "active": 1,
// //         "created_at": "2023-09-26T19:08:01.000000Z",
// //         "updated_at": "2023-09-26T19:08:01.000000Z",
// //         "deleted_at": null
// //       },
// //       "quantity": null,
// //       "unitPrice": null,
// //       "decimalPrice": null,
// //       "lineDiscountLimit": null,
// //       "packageType": null,
// //       "packageUnitName": null,
// //       "packageUnitQuantity": null,
// //       "packageSetName": null,
// //       "packageSetQuantity": null,
// //       "packageSupersetName": null,
// //       "packageSupersetQuantity": null,
// //       "packagePaletteName": null,
// //       "packagePaletteQuantity": null,
// //       "packageContainerName": null,
// //       "packageContainerQuantity": null,
// //       "decimalQuantity": null,
// //       "active": 1
// //     },
// //     {
// //       "id": 17,
// //       "company": {
// //         "id": 1,
// //         "name": "Code Caesar",
// //         "active": 1,
// //         "deleted_at": null,
// //         "created_at": "2023-07-19T16:18:12.000000Z",
// //         "updated_at": "2023-07-19T16:18:12.000000Z"
// //       },
// //       "warehouse": null,
// //       "itemType": {
// //         "id": 1,
// //         "name": "Regular",
// //         "created_at": "2023-07-19T16:06:10.000000Z",
// //         "updated_at": "2023-07-19T16:06:10.000000Z"
// //       },
// //       "mainCode": "dedede",
// //       "printMainCode": 1,
// //       "taxation": null,
// //       "subref_id": null,
// //       "canBeSold": 0,
// //       "canBePurchased": 0,
// //       "warranty": 0,
// //       "lastAllowedPurchaseDate": null,
// //       "shortDescription": null,
// //       "mainDescription": null,
// //       "secondLanguageDescription": null,
// //       "supplierCodes": [],
// //       "alternativeCodes": [],
// //       "barcode": [],
// //       "unitCost": null,
// //       "decimalCost": null,
// //       "currency": {
// //         "id": 3,
// //         "company_id": 1,
// //         "name": "USD",
// //         "symbol": "\$",
// //         "active": 1,
// //         "created_at": "2023-09-26T19:08:01.000000Z",
// //         "updated_at": "2023-09-26T19:08:01.000000Z",
// //         "deleted_at": null
// //       },
// //       "quantity": null,
// //       "unitPrice": null,
// //       "decimalPrice": null,
// //       "lineDiscountLimit": null,
// //       "packageType": null,
// //       "packageUnitName": null,
// //       "packageUnitQuantity": null,
// //       "packageSetName": null,
// //       "packageSetQuantity": null,
// //       "packageSupersetName": null,
// //       "packageSupersetQuantity": null,
// //       "packagePaletteName": null,
// //       "packagePaletteQuantity": null,
// //       "packageContainerName": null,
// //       "packageContainerQuantity": null,
// //       "decimalQuantity": null,
// //       "active": 1
// //     },
// //     {
// //       "id": 18,
// //       "company": {
// //         "id": 1,
// //         "name": "Code Caesar",
// //         "active": 1,
// //         "deleted_at": null,
// //         "created_at": "2023-07-19T16:18:12.000000Z",
// //         "updated_at": "2023-07-19T16:18:12.000000Z"
// //       },
// //       "warehouse": null,
// //       "itemType": {
// //         "id": 1,
// //         "name": "Regular",
// //         "created_at": "2023-07-19T16:06:10.000000Z",
// //         "updated_at": "2023-07-19T16:06:10.000000Z"
// //       },
// //       "mainCode": "swqqqqqqq",
// //       "printMainCode": 1,
// //       "taxation": null,
// //       "subref_id": null,
// //       "canBeSold": 0,
// //       "canBePurchased": 0,
// //       "warranty": 0,
// //       "lastAllowedPurchaseDate": null,
// //       "shortDescription": null,
// //       "mainDescription": null,
// //       "secondLanguageDescription": null,
// //       "supplierCodes": [],
// //       "alternativeCodes": [],
// //       "barcode": [],
// //       "unitCost": null,
// //       "decimalCost": null,
// //       "currency": {
// //         "id": 3,
// //         "company_id": 1,
// //         "name": "USD",
// //         "symbol": "\$",
// //         "active": 1,
// //         "created_at": "2023-09-26T19:08:01.000000Z",
// //         "updated_at": "2023-09-26T19:08:01.000000Z",
// //         "deleted_at": null
// //       },
// //       "quantity": null,
// //       "unitPrice": null,
// //       "decimalPrice": null,
// //       "lineDiscountLimit": null,
// //       "packageType": null,
// //       "packageUnitName": null,
// //       "packageUnitQuantity": null,
// //       "packageSetName": null,
// //       "packageSetQuantity": null,
// //       "packageSupersetName": null,
// //       "packageSupersetQuantity": null,
// //       "packagePaletteName": null,
// //       "packagePaletteQuantity": null,
// //       "packageContainerName": null,
// //       "packageContainerQuantity": null,
// //       "decimalQuantity": null,
// //       "active": 1
// //     },
// //     {
// //       "id": 19,
// //       "company": {
// //         "id": 1,
// //         "name": "Code Caesar",
// //         "active": 1,
// //         "deleted_at": null,
// //         "created_at": "2023-07-19T16:18:12.000000Z",
// //         "updated_at": "2023-07-19T16:18:12.000000Z"
// //       },
// //       "warehouse": null,
// //       "itemType": {
// //         "id": 1,
// //         "name": "Regular",
// //         "created_at": "2023-07-19T16:06:10.000000Z",
// //         "updated_at": "2023-07-19T16:06:10.000000Z"
// //       },
// //       "mainCode": "aaaaaaa",
// //       "printMainCode": 1,
// //       "taxation": null,
// //       "subref_id": null,
// //       "canBeSold": 0,
// //       "canBePurchased": 0,
// //       "warranty": 0,
// //       "lastAllowedPurchaseDate": null,
// //       "shortDescription": null,
// //       "mainDescription": null,
// //       "secondLanguageDescription": null,
// //       "supplierCodes": [],
// //       "alternativeCodes": [],
// //       "barcode": [],
// //       "unitCost": null,
// //       "decimalCost": null,
// //       "currency": {
// //         "id": 3,
// //         "company_id": 1,
// //         "name": "USD",
// //         "symbol": "\$",
// //         "active": 1,
// //         "created_at": "2023-09-26T19:08:01.000000Z",
// //         "updated_at": "2023-09-26T19:08:01.000000Z",
// //         "deleted_at": null
// //       },
// //       "quantity": null,
// //       "unitPrice": null,
// //       "decimalPrice": null,
// //       "lineDiscountLimit": null,
// //       "packageType": null,
// //       "packageUnitName": null,
// //       "packageUnitQuantity": null,
// //       "packageSetName": null,
// //       "packageSetQuantity": null,
// //       "packageSupersetName": null,
// //       "packageSupersetQuantity": null,
// //       "packagePaletteName": null,
// //       "packagePaletteQuantity": null,
// //       "packageContainerName": null,
// //       "packageContainerQuantity": null,
// //       "decimalQuantity": null,
// //       "active": 1
// //     },
// //     {
// //       "id": 20,
// //       "company": {
// //         "id": 1,
// //         "name": "Code Caesar",
// //         "active": 1,
// //         "deleted_at": null,
// //         "created_at": "2023-07-19T16:18:12.000000Z",
// //         "updated_at": "2023-07-19T16:18:12.000000Z"
// //       },
// //       "warehouse": null,
// //       "itemType": {
// //         "id": 1,
// //         "name": "Regular",
// //         "created_at": "2023-07-19T16:06:10.000000Z",
// //         "updated_at": "2023-07-19T16:06:10.000000Z"
// //       },
// //       "mainCode": "llllll",
// //       "printMainCode": 1,
// //       "taxation": null,
// //       "subref_id": null,
// //       "canBeSold": 0,
// //       "canBePurchased": 0,
// //       "warranty": 0,
// //       "lastAllowedPurchaseDate": null,
// //       "shortDescription": null,
// //       "mainDescription": null,
// //       "secondLanguageDescription": null,
// //       "supplierCodes": [],
// //       "alternativeCodes": [],
// //       "barcode": [],
// //       "unitCost": null,
// //       "decimalCost": null,
// //       "currency": {
// //         "id": 3,
// //         "company_id": 1,
// //         "name": "USD",
// //         "symbol": "\$",
// //         "active": 1,
// //         "created_at": "2023-09-26T19:08:01.000000Z",
// //         "updated_at": "2023-09-26T19:08:01.000000Z",
// //         "deleted_at": null
// //       },
// //       "quantity": null,
// //       "unitPrice": null,
// //       "decimalPrice": null,
// //       "lineDiscountLimit": null,
// //       "packageType": null,
// //       "packageUnitName": null,
// //       "packageUnitQuantity": null,
// //       "packageSetName": null,
// //       "packageSetQuantity": null,
// //       "packageSupersetName": null,
// //       "packageSupersetQuantity": null,
// //       "packagePaletteName": null,
// //       "packagePaletteQuantity": null,
// //       "packageContainerName": null,
// //       "packageContainerQuantity": null,
// //       "decimalQuantity": null,
// //       "active": 1
// //     }
// //   ],
// //   "links": {
// //     "first": "http://127.0.0.1:8000/api/items?page=1",
// //     "last": "http://127.0.0.1:8000/api/items?page=4",
// //     "prev": null,
// //     "next": "http://127.0.0.1:8000/api/items?page=2"
// //   },
// //   "meta": {
// //     "current_page": 1,
// //     "from": 1,
// //     "last_page": 4,
// //     "links": [
// //       {
// //         "url": null,
// //         "label": "&laquo; Previous",
// //         "active": false
// //       },
// //       {
// //         "url": "http://127.0.0.1:8000/api/items?page=1",
// //         "label": "1",
// //         "active": true
// //       },
// //       {
// //         "url": "http://127.0.0.1:8000/api/items?page=2",
// //         "label": "2",
// //         "active": false
// //       },
// //       {
// //         "url": "http://127.0.0.1:8000/api/items?page=3",
// //         "label": "3",
// //         "active": false
// //       },
// //       {
// //         "url": "http://127.0.0.1:8000/api/items?page=4",
// //         "label": "4",
// //         "active": false
// //       },
// //       {
// //         "url": "http://127.0.0.1:8000/api/items?page=2",
// //         "label": "Next &raquo;",
// //         "active": false
// //       }
// //     ],
// //     "path": "http://127.0.0.1:8000/api/items",
// //     "per_page": 10,
// //     "to": 10,
// //     "total": 35
// //   }
// // };
